import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Wormhole DAO
        </h1>

        <p className={styles.description}>
          Test firebase functions by clicking the button
        </p>
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" onClick={()=>{
fetch("http://127.0.0.1:5001/wormhole-cross-governance/us-central1/helloWorld")
.then(response => {
  // indicates whether the response is successful (status code 200-299) or not
  if (!response.ok) {
    throw new Error(`Request failed with status ${reponse.status}`)
  }
  return response.json()
})
.then(data => {
  console.log(data.count)
  console.log(data.products)
})
.catch(error => console.log(error))
      }}>
          Click Me!
        </button>
      </main>

      <footer className={styles.footer}>

        <Image src="/wormhole.jpg" alt="Wormhole" width={50} height={50} />


      </footer>
    </div>
  )
}
